name: Generate PDF Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push to repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install puppeteer markdown-pdf fs-extra

      - name: Generate Screenshots and PDF
        run: node scriptes/generateReport.js

      - name: Create reports folder
        run: mkdir -p reports

      - name: Move PDF to reports folder
        run: mv report.pdf reports/Report_$(date +'%Y-%m-%d_%H-%M-%S').pdf

      - name: Commit PDF to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add reports/
          git commit -m "🧾 Auto-generated report [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push
